services:
  
  api:
    container_name: api
    image: node:18-alpine
    command: sh -c "npm run server"
    ports:
      - 5000:5000
    working_dir: /api
    volumes:
      - ./:/api
    env_file:
      - .env
    depends_on:
      - database

  database:
    container_name: api_db
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      #PGDATA: ${PGDATA}
    ports:
      - 5432:5432
    volumes:
      #- docker-data-postgres:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  docker-data-postgres: